ExamWeb/Models/ErrorViewModel.cs
using System;

namespace ExamWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamWeb/Controllers/Exam1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExamWeb.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace ExamWeb.Controllers
{
    [Route("Jornadas")]
    public class Exam1Controller : Controller
    {
        private readonly ILogger<Exam1Controller> _logger;
        private readonly MyDbContext _context;

        public Exam1Controller(ILogger<Exam1Controller> logger, MyDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        [HttpGet]
        [Route("")]
        [Route("Index")]
        [Route("Jornadas/Index")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("GetJournadas")]
        public async Task<IActionResult> GetJourneys(JourneyFilterVM filter)
        {
            var model = new JourneyListVM()
            {
                Journeys = await _context.Journeys.Where(s => s.End >= filter.From && s.End <= filter.To).Select(s => new JourneyVM()
                {
                    DataFinal = s.End,
                    DataInicial = s.Start,
                    DriverName = s.DriverName,
                    Id = s.Id
                }).ToListAsync()
            };

            return PartialView("_ListOfJourneys", model);
        }
    }

    public class JourneyListVM
    {
        public List<JourneyVM> Journeys { get; set; }
    }

    public class JourneyVM
    {
        public int Id { get; set; }
        public string DriverName { get; set; }
        public DateTime DataInicial { get; set; }
        public DateTime DataFinal { get; set; }
    }

    public class JourneyFilterVM
    {
        public DateTime From { get; set; }
        public DateTime To { get; set; }
    }
}

ExamWeb/Controllers/Exam2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExamWeb.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace ExamWeb.Controllers
{
    [Route("Motoristas")]
    public class Exam2Controller : Controller
    {
        private readonly ILogger<Exam2Controller> _logger;
        private readonly MyDbContext _context;

        public Exam2Controller(ILogger<Exam2Controller> logger, MyDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        [HttpGet]
        [Route("")]
        [Route("Index")]
        [Route("Motoristas/Index")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("GetDetailsOfEach")]
        public async Task<IActionResult> GetDetailsOfEach(List<int> ids)
        {
            var model = new JourneyListVM()
            {
                Journeys = await _context.Journeys.Where(s => ids.Contains(s.Id)).Select(s => new JourneyVM()
                {
                    DataFinal = s.End,
                    DataInicial = s.Start,
                    DriverName = s.DriverName,
                    Id = s.Id
                }).ToListAsync()
            };

            return new JsonResult(model);
        }
    }
}

ExamWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ExamWeb.Models;

namespace ExamWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamWeb/Views/Exam1/Index.cshtml
@model ExamWeb.Controllers.JourneyFilterVM
@{
    ViewBag.Title = "Jornadas";
}

<div class="jumbotron">
    <h2>@ViewBag.Title</h2>
    <hr />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Serviços</a></li>
            <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
        </ol>
    </nav>
</div>

@await Html.PartialAsync("_JourneyFilter", Model)

<div class="jumbotron">
    <div id="reportResult">
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            intialSetup();
            setupValidation();
        });

        function setupValidation() {
            var validator = $('#akrual-form').validate({
                submitHandler: function (form) {
                    $('#spinner-report').show();

                    const $form = $(form);
                    // serialize the data in the form
                    const serializedData = $form.serialize();

                    $.ajax({
                        url: "/Journeys/GetJournadas/",
                        type: "POST",
                        data: serializedData,

                    }).done(function (response) {
                        newReportArrived(response);
                    }).always(function (response) {
                        alwaysCallback();
                    });
                }
            });
        }

        function newReportArrived(response) {
            $('#reportResult').html(response);
            createTable();
        }

        function alwaysCallback() {
            $('#spinner-report').hide();
        }

        function intialSetup() {
            $('#To').datepicker({
                language: 'pt-BR',
                date: new Date(2019, 10, 30),
                autoPick: true
            });

            $('#From').datepicker({
                language: 'pt-BR',
                date: new Date(2018, 9, 30),
                autoPick: true
            });

            $('#spinner-report').hide();
        }

        function createTable() {
            $('.footable').DataTable({
                "lengthMenu": [[10, 25, -1], [10, 25, "All"]],
                "scrollX": true,
                "order": [[2, 'asc']]
            });
        }
    </script>
}

ExamWeb/Views/Exam1/_JourneyFilter.cshtml
@model ExamWeb.Controllers.JourneyFilterVM


<div class="jumbotron">
    <h5>Filtros para Consulta</h5>
    <hr/>
    @using (Html.BeginForm("GetJourneys", "Journeys", FormMethod.Post, new { @class = "form-horizontal", role = "form", @id = "akrual-form" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("IsAPost", true)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.From, htmlAttributes: new { @class = "control-label col-md-2" })
            <input name="From" id="From" data-toggle="datepicker">
            @Html.ValidationMessageFor(model => model.From, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.To, htmlAttributes: new { @class = "control-label col-md-2" })
            <input name="To" id="To" data-toggle="datepicker">
            @Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
        </div>

        <input id="refreshReport" name="listButton" value="Consultar" type="submit" class="btn btn-primary">

        <div id="spinner-report" hidden>
            <div class="sk-spinner sk-spinner-pulse"></div>
        </div>
    }
</div>

ExamWeb/Views/Exam1/_ListOfJourneys.cshtml
@model ExamWeb.Controllers.JourneyListVM


@if (Model.Journeys != null &&
    Model.Journeys.Any())
{
    <table class="table table-striped table-bordered table-hover footable dataTables_scrollBody" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Motorista
                </th>
                <th>
                    Início
                </th>
                <th>
                    Fim
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Journeys)
            {
                <tr dataid="@item.Id">
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.DriverName
                    </td>
                    <td>
                        @Html.DisplayFor(s => item.DataInicial, "DateTimeWithTime")
                    </td>
                    <td>
                        @Html.DisplayFor(s => item.DataFinal, "DateTimeWithTime")
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "Journeys", new { id = item.Id })" class="btn btn-sm btn-primary"><i class="fa fa-pencil"></i>&nbsp;Editar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>Nenhum resultado.</h3>
}

ExamWeb/Views/Exam2/Index.cshtml
@model ExamWeb.Controllers.JourneyFilterVM
@{
    ViewBag.Title = "Jornadas";
}

<div class="jumbotron">
    <h2>@ViewBag.Title</h2>
    <hr />
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Serviços</a></li>
            <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
        </ol>
    </nav>
</div>

<div class="jumbotron">
    <table class="table table-striped table-bordered table-hover footable dataTables_scrollBody" cellspacing="0" width="100%" role="grid" aria-describedby="example_info" style="width: 100%;">
        <thead>
            <tr>
                <th></th>
                <th>
                    Id
                </th>
                <th>
                    Motorista
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><input type="checkbox" data-id="1" class="i-checks selectedBordero" /><br></td>
                <td>
                    1
                </td>
                <td>
                    Motorista Exemplo 1
                </td>
            </tr>
            <tr>
                <td><input type="checkbox" data-id="2" class="i-checks selectedBordero" /><br></td>
                <td>
                    2
                </td>
                <td>
                    Motorista Exemplo 2
                </td>
            </tr>
            <tr>
                <td><input type="checkbox" data-id="3" class="i-checks selectedBordero" /><br></td>
                <td>
                    3
                </td>
                <td>
                    Motorista Exemplo 3
                </td>
            </tr>
            <tr>
                <td><input type="checkbox" data-id="4" class="i-checks selectedBordero" /><br></td>
                <td>
                    4
                </td>
                <td>
                    Motorista Exemplo 4
                </td>
            </tr>
        </tbody>
    </table>
    <div class="ibox-content">
        <button class="btn btn-success" id="gotoMontarCarteira">Buscar Detalhes</button>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        var selectedBorderos = [];
        $(document).ready(function () {
            intialSetup();
        });

        function intialSetup() {
             $("#gotoMontarCarteira").click(function (event) {
                var allBorderos = $('.selectedBordero').toArray().map(item => {
                    var result = {};
                    result.selected = item.checked;
                    var borderoId = parseInt($(item).data("id"));
                    result.borderoId = borderoId;
                    return result;
                });

                var selectedBorderos = allBorderos.filter(s => s.selected).map(s => s.borderoId);

                var url = '@Url.Action("GetDetailsOfEach", "Exam2")?ids=' + selectedBorderos;
                 window.location.replace(url);

             });
        }
    </script>
}

ExamWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExamWeb/Views/Shared/DisplayTemplates/DateTimeWithTime.cshtml
@model DateTime?
@{
    if (Model != null)
    {
        <p style="display: none">@Model.Value.ToString("yyyyMMddHHmm")</p>
        <span class="date">@Model.Value.ToString("dd/MM/yy HH:mm")</span>
    }
}

ExamWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="~/lib/datePicker/datepicker.min.css" />
    <link rel="stylesheet" href="~/lib/dataTables/datatables.min.css" />
    @RenderSection("Styles", required: false)


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.mask.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/datePicker/datepicker.min.js"></script>
    <script src="~/lib/datePicker/datepicker.pt-BR.js"></script>
    <script src="~/lib/dataTables/datatables.min.js"></script>

    @RenderSection("PageScriptLoader", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Jornadas">Exam 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Motoristas">Exam 2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ExamWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>